package fr.hugosimony.lguhc.player;

public enum Role {
	ANCIEN, ASSASSIN, CHASSEUR, CUPIDON, DETECTIVE, ENFANT_SAUVAGE, IPDL, LG, LG_AMNESIQUE, LG_ANONYME, LGB, PARANO, PF, RENARD, SALVA, SOEUR, SORCIERE, SV, VOLEUR, VOYANTE, VPL, NONE, INIT
}
